### PR TITLE
integrated rubocop with customized config and auto-fixes

### PR DESCRIPTION
**Pull request by srizvi-official**
[Rubocop](http://rubocop.readthedocs.io/en/latest/configuration/)
- .rubocop.yml can be used to configure how the style should be and what to analyze
- .rubocop.yml takes precedence over rubocop's default configuration
- run `rubocop` to analyze the code in the root directory and `rubocop path/to/file` to inspect specific one
- run `rubocop --auto-correct` to auto correct the offenses. 119 offences are corrected automatically as per the current config. The remaining should be corrected manually. However, some of them are ractified manually in this PR.

### CODE REVIEW

**Comment by srizvi-official** [comment]
By default Rubocop identify issue's as per standard styling guide over there https://github.com/bbatsov/rubocop/blob/master/config/default.yml .

If we wanted to disable specific styling and wanted to alter as per our needs than, we can override it in .rubocop.yml .

I made some modifications over there just for example. You are welcome to add or subtract these rules.

**Comment by srizvi-official** [comment]
I rectified some of of them manually which auto correct feature can't fix.

But, there are some offences in your code as well, which I left intentionally so that we can review whether we need to fix them or ignore. once our configuration file mature than we all strictly follow that before generating PRs and help us to be consistent.

**Comment by mckinley** [comment]
I worry that this is not going to be useful until rubocop can run and be green. I don't think this issue can be complete without starting off with a green status. Otherwise how is a developer expected to notice and fix problems that are newly identified. I feel the same about `standard`, the js-linter.

I felt fine committing `standard` to master because at least the rules are not meant to be configured. And there were no auto-fixes in the commit. Rubocop has more configuration and I would also like to have a say in what rules we use. So having an unfinished configuration, red build, and auto-fixes in place make me not want to commit this.

I also de-prioritized this issue and I feel strongly that it should remain that way. Rubocop has simple commands to generate a todo file that ignores existing problems. We can add this at any time. I don't think code style should be a priority right now. And these linting chores were not meant to be addressed until there was nothing else in the backlog. As I have said before, I don't want any more work going into this for now.

Sorry, but I am going to close this. We can leave the branch up incase we want to use any of the code later on when this is more of a priority.

**Comment by srizvi-official** [comment]
We can configure rules in configurations and auto fix as per new rule set . As its help all us in following uniform style. But priority is your call, we defer this for now. But, surely leave that open as soon as you able to select style appropriate for this project we can add those and merge it.

**Pull request closed without merging**
