### PR TITLE
Jest with test cases

### PR DESCRIPTION
**Pull request by srizvi-official**
This PR contains Jest integration along with test cases for React Components. We have used [Enzyme](http://airbnb.io/enzyme/index.html) and [react-addons-test-utils](https://facebook.github.io/react/docs/test-utils.html) for component testing.
- Run `yarn` to install dependencies
- Run `yarn test` to execute all test suites
- Run `yarn test <path/to/test/script>`
- Jest configuration can be found in /config/jest/config.json

### CODE REVIEW

**Comment by srizvi-official** [comment]
as far as __test__ directory naming scheme concern we adopt that from Jest available documentation

**Zero configuration**

Jest is already configured when you use create-react-app or react-native init to create your React and React Native projects. Place your tests in a **__tests__** folder, or name your test files with a .spec.js or .test.js extension. Whatever you prefer, Jest will find and run your tests.

**Comment by srizvi-official** [comment]
Unit test also part of this PR for all the functionality written so far in reactJS for all developers. Going forward developers should use this foundation to write their unit test, pre-written test can be consider as example.

There are some conflicts in yarn file which are resolve now.

**Comment by srizvi-official** [comment]
Once we all familiar with it, we can make it part of rake, intentionally holding it for now so that you can review it and if there are any suggestion incase i will incorporate those than we can make it part of rake going forward.

reason for focusing on things like Ruby Linter, JS linter & Jest (Javascript unit test) because I want foundation to be in place so all of us following it from day one and avoid technical debt.

Furthermore, these styling help us to avoid issue we just face related to styling and consistency.

Work on feature user stories is already in place and other developer focusing more on that part.

**Comment by srizvi-official** [comment]
Also added some wiki pages with details, how to use these utilities just for documentation purposes. we will improve it down the road right it has just some basic info.

**Comment by mckinley** [comment]
@srizvi-official this is fantastic! Thank you for putting this together so well!

**Comment by mckinley** [comment]
Also I think we should just add this to rake! Great work!

**Pull request merged**
