### PR TITLE
Revert "Revert "CSS restructuring.""

### PR DESCRIPTION
**Pull request by mckinley**
Reverts bionic-solution/bionic-dashboard#26

Hah! So sorry @aqadir-cc I merged this in before it was ready! I didn't notice it didn't have a "ready for review" tag. Whoops. This PR is to revert the revert (so commit your original changes to master). You can use this branch to continue working on it.

`revert-26-revert-24-fursid/css-restructuring-2/#143494261`

### CODE REVIEW

**Comment by aqadir-cc** [comment]
Noted. will do so.

**Comment by aqadir-cc** [comment]
@mckinley I'll use check out this branch to finalize my work and label this PR when it's ready for review.

**Comment by mckinley** [comment]
Sorry I want to keep all communication about an issue either here or on PT. I forget sometimes though... @aqadir-cc no need to re-read. This is just our Slack conversation.
Slack correspondence:

```
bronson [1 day ago] 
@fursid how is the portfolio header coming? There are some formatting additions like turning 1,000,000 into $1M etc that are not in the engineering commits. They are simple to add. @srizvi has already put functions for that in lib and they just need to be added. Are you adding them as a part of the design story?

fursid [22 hours ago] 
I will look into it after i'm done with some CSS restructuring task i'm doing.
```

**Comment by mckinley** [comment]
@aqadir-cc Id like to see either this branch or the OA header branch merged into master so we can resolve conflicts they are going to make for each other.

I can also jump in and help! I would have prefered that we leave the files outside of directories "modules" and "partials" because those directories seem ambiguous and probably not needed, and only using the "components" directory for the styling of react components inside "react/components". If you agree, I can do this in under 10 minutes, so let me know if I can help. If you would rather have them inside the directories that you created thats totally fine too! But lets get this into master soon. Its going to create a lot of conflicts for other stories.

Thanks!

**Comment by aqadir-cc** [comment]
@mckinley I agree. I'm fine with moving them out too for the purpose of keeping it as flat as possible if current set up looks confusing. We can only keep components in a folder to separate them. Yeah I think this needs to be merged sooner than later to avoid further complications. Please go ahead with the folder structure you just mentioned and merge it afterwards.

**Comment by mckinley** [comment]
Yay thanks!

**Comment by mckinley** [comment]
@aqadir-cc I pulled your branch to make the changes, but the styling is messed up on portfolio header. Is that ok? Is the fix for this in another branch maybe? Just want to make sure you are aware:

screen shot 2017-04-12 at 8 44 10 am

**Comment by aqadir-cc** [comment]
Yes @mckinley, those changes are available in another branch. This was only the re-structuring branch without any changes to particular components.

**Comment by aqadir-cc** [comment]
This is already merged into #29

**Pull request merged**
